<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="" dir="">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
        <meta charset="utf-8">
        <title>Forum</title>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    </head>
    <body> 
        <form action="newfile.php" method="get" name="form">
                <h1 align="center">Entrance to the forum</h1>
                <div align="center">
                        <div>Enter Email:</div>
                        <div><input type="text" size="20" id="email2" name="email" maxlength="20" /></div>
                        <div>Enter Password:</div>
                        <div><input type="text" size="20" id="password" name="password" maxlength="20" /></div>
                </div>
                <div align="center">
                        <div><input name="submit" type="hidden" value="1" /><input id="js_button" type="submit" name="enter" value="Enter" /></div>
                </div>
        </form>
    </body>
</html>