<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="" dir="">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
        <meta charset="utf-8">
        <link rel="stylesheet" href="style.css" type="text/css"/>
        <title></title>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>      
    </head>
    <body>
        <table class="parent">
            <tr>
                <td>
                    <a href="index.php?action=register">Registration</a>
                </td>
                <td>
                    <a href="index.php?action=login">Login</a>
                </td>
                <td>
                    Search
                </td>
                <td>
                    <input name="keywords" type="text" maxlength="28">
                </td>
            </tr>
        </table> 
        <form action="community.php?action=variable_topic&parent_id=56" method="get" >
<?php
$action='';

include_once 'variables.php';

if (isset ($_GET['parent_id'])){
    $parent_id=$_GET['parent_id'];
}else {
    $parent_id="0";
}

if (isset($_GET['action']) && file_exists($_GET['action'].".php")) {
	$action=$_GET['action'];	 
	include_once $action.'.php';
}elseif (isset($_GET['action']) && !file_exists($_GET['action'].".php")) {
	include_once 'not_found.phtml';
}else {
	include_once 'variable_topic.php';
}
?>      
        </form>                 
    </body>
</html>    