<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="" dir="">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
        <meta charset="utf-8">
        <link rel="stylesheet" href="style.css" type="text/css"/>
        <title></title>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>      
    </head>
    <body>
        <table class="parent">
            <tr>
                <td>
                    <a href="index.php?action=register">Registration</a>
                </td>
                <td>
                    <a href="index.php?action=login">Login</a>
                </td>
                <td>
                    Search
                </td>
                <td>
                    <input name="keywords" type="text" maxlength="28">
                </td>
            </tr>
        </table>
         <table class="child">
            <tr>
                <td width="17%">
                    <a class="menu" href="index.php?action=community">General</a>
                </td>
                <td width="17%">
                    <a class="menu" href="index.php?action=page_not">Forums</a>
                </td>
                <td width="17%">
                    <a class="menu" href="index.php?action=page_not">Files</a>
                </td>
                <td width="16%">
                    <a class="menu" href="index.php?action=page_not">Info Base</a>
                </td>
                 <td width="18%">
                    <a class="menu" href="index.php?action=page_not">Documentation</a>
                </td>
                 <td>
                    <a class="menu" href="index.php?action=page_not">FAQ</a>
                </td>
            </tr>
        </table>
<?php
$action='';

include_once 'variables.php';

if (isset($_GET['action']) && file_exists($_GET['action'].".php")) {
	$action=$_GET['action'];	 
	include_once $action.'.php';
}elseif (isset($_GET['action']) && !file_exists($_GET['action'].".php")) {
	include_once 'not_found.phtml';
}else {
	include_once 'community.php';
}

if (isset ($_GET['parent_id'])){
    $action=$_GET['parent_id'];
}else {
    $_GET['parent_id']="0";
}
?>
        <form action="community.php" method="get" >
            <div class="forumc">
                <input type="hidden"  name="action" value="variable_topic" />
                <input class="b1" align="middle" type="submit" value="NEW TOPIC"/>
                <p>Coment<Br><textarea name="texttopic" cols="25" rows="3" pattern="^[a-zA-Z]+$"></textarea></p>
            </div>
        </form>
        <table class="general">
            <tr>
                <td class="color">
                    <a class="menu" href="index.php?action=page_not">New</a>
                </td>
                <td class="color" width="5%">
                    <a class="menu" href="index.php?action=page_not">Topics</a>
                </td>
                <td class="color" width="5%">
                    <a class="menu" href="index.php?action=page_not">Messages</a>
                </td>
                <td class="color" width="30%">
                    <a class="menu" href="index.php?action=page_not">The latest posts</a>
                </td>
            </tr>
            <tr>
                <td class="left">
                    <a class="menu" href="index.php?action=pet">Pet Battles</a>
                </td>
                <td>                    
                </td>
                <td>                    
                </td>
                <td>                    
                </td>
            </tr>
            <tr>
                <td class="color">
                    <a class="menu" href="index.php?action=page_not">General Forums</a>
                </td>
                <td class="color">
                    <a class="menu" href="index.php?action=page_not">Topics</a>
                </td>
                <td class="color">
                    <a class="menu" href="index.php?action=page_not">Messages</a>
                </td>
                <td class="color">
                    Technical Support
                </td>
            </tr>
            <tr>
                <td class="left">
                    <a class="menu" href="index.php?action=page_not">Technical Support</a>
                </td>
                <td>                    
                </td>
                <td>                    
                </td>
                <td>                    
                </td>
            </tr>
            <tr>
                <td class="color">
                    <a class="menu" href="index.php?action=page_not">PHP</a>
                </td>
                <td class="color">
                    <a class="menu" href="index.php?action=page_not">Topics</a>
                </td>
                <td class="color">
                    <a class="menu" href="index.php?action=page_not">Messages</a>
                </td>
                <td class="color">
                    <a class="menu" href="index.php?action=page_not">The latest posts</a>
                </td>
            </tr>
            <tr>
                <td class="left">
                    <a class="menu" href="index.php?action=page_not">Little about PHP</a>
                </td>
                <td>                    
                </td>
                <td>                    
                </td>
                <td>                    
                </td>
            </tr>
            <tr>
                <td class="color">
                    <a class="menu" href="index.php?action=page_not">Private forums</a>
                </td>
                <td class="color">
                    <a class="menu" href="index.php?action=page_not">Topics</a>
                </td>
                <td class="color">
                    <a class="menu" href="index.php?action=page_not">Messages</a>
                </td>
                <td class="color">
                    <a class="menu" href="index.php?action=page_not">The latest posts</a>
                </td>
            </tr>
            <tr>
                <td class="left">
                    <a class="menu" href="index.php?action=page_not">General Beta Feedback</a>
                </td>
                <td>                    
                </td>
                <td>                    
                </td>
                <td>                    
                </td>
            </tr>
        </table>        
    </body>
</html>    