<form action="login.php" method="get" name="forma">
	<h1 align="center">Entrance to the forum</h1>
	<div align="center">
		<div>Enter Email:</div>
		<div><input type="text" size="20" id="email2" name="email" maxlength="20" /></div>
		<div>Enter Password:</div>
		<div><input type="text" size="20" id="password" name="password" maxlength="20" /></div>
	</div>
	<div align="center">
		<div><input name="submit" type="hidden" value="1" /><input id="js_button" type="submit" name="enter" value="Enter" /></div>
	</div>
</form>

<form action="forum.php" method="post" name="forma2">
	<div align="center">
		<div><input id="js_button2" type="submit" name="reg" value="Registration for the forum" /></div>
	</div>
</form>

<script type="text/javascript">
            $( document ).ready(function() {
                $( "#js_button" ).click(function() {
                    var lname=$('#password').val();
                    if (lname.length<1) {
                            alert("please fill password field");
                            jQuery("#password").css("background-color", "red");
                    }
                 });
            });
            $( document ).ready(function() {
             $( "#js_button" ).click(function() {
                    var lname=$('#email2').val();
                    if (lname.length<1) {
                            alert("please fill email field");
                            jQuery("#email2").css("background-color", "red");
                    }
                 });
            }); 
</script>
