<body>
    <header id="header">
        <div class="header-bar">
            <div class="conteiner">
                <div class="header-log">
                    <a class="header-brand">
                        <img src="" alt="альтернативный текст">
                    </a>           
                </div>
                <nav id="navigation-menu" role="navigation">
                    <ul class="header-navigation">
                        <il>
                            <a id="gotohome" class="" href="#"></a>
                        </il>
                        <il>
                            <a id="gotoabout" class="" href="#"></a>
                        </il>
                        <il>
                            <a id="gotofeatures" class="" href="#"></a>
                        </il>
                        <il>
                            <a id="gotoworks" class="" href="#"></a>
                        </il>
                        <il>
                            <a id="gotopricing" class="" href="#"></a>
                        </il>
                        <il>
                            <a id="gototeam" class="" href="#"></a>
                        </il>
                        <il>
                            <a id="gotoblog" class="" href="#"></a>
                        </il>
                        <il>
                            <a id="gotocontacts" class="" href="#"></a>
                        </il>
                    </ul>
                </nav>
            
            </div>
            
        </div>
    </header>
        
</body>