
<?php if (count($messages)): ?>
<table align="center" border="1">
	<?php foreach ($messages as $topic_val):?>
	<tr>
		<td><?php  echo $topic_val['messages'] ?></td>
	</tr>
	<?php endforeach;?>
</table>
<?php else: ?>
<center>
	<h1>No messages</h1>
</center>
<?php endif; ?>


<table align="center" border="1">
	<tr>
		<td>
			<form action="index.php?action=messages" method="post">
				<input type="hidden" name="parent_id" value="<?php echo $parent_id;?>" />
				<textarea name="message_text"></textarea>
				<input type="submit" value ="Add" />
			</form>
		</td>
	</tr>
</table>