<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="" dir="">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
        <meta charset="utf-8">
        <link rel="stylesheet" href="css/style.css" type="text/css"/>
        <title>Forum</title>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    </head>
    <body>
        <table class="parent">
            <tr>
                <td>
                    <a href="index.php?action=register">Registration</a>
                </td>
                <td>
                    <a href="index.php?action=login">Login</a>
                </td>
                <td>
                    Search
                </td>
                <td>
                    <input name="keywords" type="text" maxlength="28">
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td class="color">
                    <a href="index.php">General Page</a>
                </td>                
            </tr>
        </table>  