<?php echo $messages_added; ?>
<?php if(count($mesages)) ?>
<table>
    <?php foreach($messages as $topic_val): ?>
    <tr>
        <td><?php echo $topic_val['messages'] ?></td>
    </tr>
    <?php endforeach; ?>
    <?php else: ?>
    <center>
        <h1>No Messages</h1>
    </center>
    <?php endif; ?>
</table>

<table align="center" border="1">
    <tr>
        <td>
            <form action="index.php?action=messages" method="post" >
                <input type="hidden" name="parent_id" value="<?php echo $parent_id ?>" />
                <textarea type="" name="messages_text" value="" ></textarea>
                <input type="submit" value="add"/>
            </form>
        </td>
    </tr>
</table>