<?php echo $message_added; ?>
<?php if(count($messages)):?>
<table>
    <?php foreach($message as $topic_val): ?>
    <tr>
        <td><?php echo $topic_val['messages'] ?></td>
    </tr>
    <?php endforeach; ?>
</table>
<?php else : print_r($message); echo $topic_val;?>
<center>
    <h1>No Messages</h1>
</center>
<?php endif; echo $parent_id; ?>
<table align="center" border="1">
    <tr>
        <td>
            <form action="index.php?action=messages" method="post">
                <input type="hidden" name="parent_id" value="<?php echo $parent_id; ?>" />
                <textarea name="messages_text"></textarea>
                <input type="submit" value="add" />
            </form>
        </td>
    </tr>
</table>


