<?php echo $messages_added;  ?>
<?php if (count($messages)): ?>
<tables>
    <?php foreach($messages as $topic_val): ?>
    <tr>
        <td><?php echo $topic_val['messages']; ?></td>
    </tr>
    <?php endforeach; ?>
</tables>
<?php else: ?>
<center>
    <h1>No Messages</h1>
</center>
<?php endif; ?>
<table allign="center" border="1">
    <tr>
        <td>
            <form action="index.php?action=messages" method="post">
                <input type="hidden" name="parent_id" value="<?php echo $parent_id ?>"/>
                <textarea name="messages_text"></textarea>
                <input type="submit" name="add" /> 
            </form>
        </td>
    </tr>
</table>
