<div class="register">
    <form action="index.php" method="get" >
        <input type="hidden"  name="action" value="login" />
        <table border="1" style="margin:auto;" bordercolor="#EEEEEE">
            <tr>
                <td class="color">Email</td>
                <td class="color"><input id="email" name="email" type="email" size="33"/></td>
            </tr>
            <tr>
                <td class="color">Password</td>
                <td class="color"><input id="password" name="password" type="text" size="33" required placeholder="Only numbers" /></td>
            </tr>
            <tr>
                <td class="color">Name</td>
                <td class="color"><input id="name" name="name" type="text" size="33" /></td>
            </tr>
            <tr>
                <td class="color">Last Name</td>
                <td class="color"><input id="lname" name="lname" type="text" size="33" /></td>
            </tr>
            <tr>
                <td class="color">Nickname</td>
                <td class="color"><input id="niname" name="nname" type="text" size="33" /></td>
            </tr>
            <tr>
                <td class="color">Date of birth</td>
                <td class="color">
                    <select name="day_b">  
                        <?php asort($day_b);?>
                        <?php  foreach ($day_b as $k=>$v): ?>
                        <option value="<?php echo $k; ?>"><?php echo $v; ?></option>
                        <?php endforeach; ?>                                                        
                    </select>  
                    <select name="month">
                        <?php asort($month);?>
                        <?php  foreach ($month as $k=>$v): ?>
                        <option value="<?php echo $k; ?>"><?php echo $v; ?></option>
                        <?php endforeach; ?>                       
                    </select>
                    <select name="year">
                        <?php asort($year);?>
                        <?php  foreach ($year as $k=>$v): ?>
                        <option value="<?php echo $k; ?>"><?php echo $v; ?></option>
                        <?php endforeach; ?>                      
                    </select>
                </td>
            </tr>
            <tr>
                <td class="color">Sex</td>
                <td class="color" id="sext"><input id="male" name="sex" type="radio" value="male" />Male
                                            <input id="female" name="sex" type="radio" value="female" />Female
                </td>
            </tr>
            <tr>
                <td class="color">Location</td>
                <td class="color">
                    <select name="location">
                        <?php asort($location);?>
                        <?php  foreach ($location as $k=>$v): ?>
                        <option value="<?php echo $k; ?>"><?php echo $v; ?></option>
                        <?php endforeach; ?>                       
                    </select>
                </td>
            </tr>
            <tr>
                <td class="color" id="f2">
                    <input id="f1" name="f1" type="checkbox" value="check">I accept Terms of Use of the ulD community<br>
                    <input name="submitted" type="hidden" value="1"/><input id="js_button" type="submit" value="Sign Up"/>
                </td>
            </tr>
        </table>                                                                                                              
    </form>
</div>